version: '3.9'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "4040:4100"
      - "9465:9465"
    depends_on:
      - user-service
      - order-service
      - payment-service
    networks: [observability]

  user-service:
    build: ./user-service
    ports:
      - "9466:9466"    
    entrypoint: []
    command: ["node", "dist/main.js"]    
    networks: [observability]

  order-service:
    build: ./order-service
    ports:
      - "9467:9467"     
    networks: [observability]

  payment-service:
    build: ./payment-service
    ports:
      - "9468:9468"      
    networks: [observability]

networks:
  observability:
    external: true
